### ISSUE TITLE
option to configure jsdom [was: Interference with existing js]

### ISSUE THREAD

**Issue by PatrickMassot** [pkra/mathjax-node-page#15]
Maybe I completely misunderstood the purpose of this project. I came here from [re-organizing the examples in /bin](https://github.com/mathjax/MathJax-node/issues/208#issuecomment-268758135) discussion, hoping to replace my use of the deprecated ``page2svg``. As explained in the linked page, I can't get any conversion. But also I noticed interference with my javascript which has nothing to do with mathjax. Consider the following ``test.html``:

```html
<head>
<meta charset="utf-8">
<title>Test mjpage</title>
</head>
<body>
Hello $x=1$.

<script src="http://code.jquery.com/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
$('body').css('background','red');
</script>
</body>
</html>
```
If I run ``cat test.html | node_modules/mathjax-node-page/bin/mjpage.js --format=TeX> out.html`` I get the error ``Error: Uncaught [ReferenceError: $ is not defined]``. It seems ``mjpage`` tries to run my inline js without downloading jQuery. The same happens if my inline js is replaced by including a local js file like ``<script type="text/javascript" src="myjs.js"></script>``.

I had no such trouble with ``page2svg`` which happily ignored my javascript and took care of my mathematics (as expected).

**Comment by pkra** [comment]
This is expected right now -- jsdom is configured to **not** fetch remote resources.

It seems reasonable to make this optional.

**Comment by pkra** [comment]
=> Renamed.

**Comment by PatrickMassot** [comment]
But I don't want mjpage to fetch this remote resources, I want it to convert my mathematics input. Here I would like it to completely ignore all my script tags. Maybe there are use cases where I would want it to do otherwise but right now I don't see them. Why didn't this issue occurred with page2svg?

Maybe an example use is better than abstract discussion. You could have a look at [this page](http://www.math.polytechnique.fr/perso/massot.patrick/enseignement/mat553/sect0012.html) for instance, generated by plasTeX+page2svg. It's full of maths (especially if you click on all +'s to open up proofs) and page2svg allow instant rendering (compared to client side mathjax which needs several seconds of page flickering due to reflow). But I don't want mathjax to care about my jquery animating the + and x which show or hide part of the page.

**Comment by pkra** [comment]
> But I don't want mjpage to fetch this remote resources,

But others might. It would be off by default anyway.

> Here I would like it to completely ignore all my script tags.

That's not possible due to the way MathJax works.

> Why didn't this issue occurred with page2svg?

It was not logging out javascript errors from the window to stdout (just MathJax errors and warnings).

**Comment by PatrickMassot** [comment]
> It was not logging out javascript errors from the window to stdout (just MathJax errors and warnings).

Is there anyway to get this behavior from mjpage? The output is really ugly whereas, from my point of view, this is not an error at all.

**Comment by pkra** [comment]
> Is there anyway to get this behavior from mjpage? 

Not at this time; it's a good feature request though.

**Comment by pkra** [comment]
Renamed slightly.

I'm not sure if the CLI tool should have options for controlling jsdom so I'd rather leave those out for now. But because there aren't CLI options, I'll disconnect the window's console from stdout in the CLI tool (to avoid JS errors from appearing in the output).

**Comment by PatrickMassot** [comment]
Thanks!
