### ISSUE TITLE
with no math on the page, the final process() call will produce an error [was: Default format is wrong]

### ISSUE THREAD

**Issue by PatrickMassot** [pkra/mathjax-node-page#16]
As mentioned in [the wrong place](https://github.com/mathjax/MathJax-node/issues/208#issuecomment-268778022), the default format option is incorrect.

**Comment by pkra** [comment]
I actually can't reproduce the problem with the code you had posted there. Could you try the latest version?

**Comment by pkra** [comment]
Correction, I can reproduce the issue after all.

**Comment by pkra** [comment]
The issue is caused by failing to account for documents without (detected) math. 

We should simply not call mathjax-node again to generate the css and globalsvg respectively.
