### ISSUE TITLE
support for mathjax's custom script type 

### ISSUE THREAD

**Issue by pkra** [pkra/mathjax-node-page#37]
Some pre-processing tools produce MathJax's custom script tags in HTML. This is currently not picked up by mathjax-node-page (which, mostly out of laziness, uses something different).

For example, kramdown (thus Jekyll and GitHub pages) does this and unfortunately will not handle markdown with MathJax output well (inserting `p`s etc).

**Comment by wilbowma** [comment]
+1, just ran into this when trying to prerender some stuff.
