### ISSUE TITLE
mathjax-node not being configured [was: MathJax.SVG.Augment.initSVG not called]

### ISSUE THREAD

**Issue by darobin** [pkra/mathjax-node-page#38]
I have just upgraded to mathjax-node-page. Part of my configuration includes a `MathJax.SVG.Augment.initSVG` override (mostly used to monkey-patch `lookupChar`). In general the configuration seems to work, but this method does not appear to be called (however I am not getting missing glyph warnings either).

Is that an expected new behaviour?

**Comment by pkra** [comment]
> Part of my configuration includes a MathJax.SVG.Augment.initSVG override 

You are referring to https://github.com/mathjax/MathJax/issues/1091#issuecomment-269653429, right?

> Is that an expected new behaviour?

Hm... sounds like a bug. I'll take a look.

**Comment by pkra** [comment]
After chasing it around a bit, I think this is a simple bug but I'll double check.

**Comment by darobin** [comment]
Yes, that is indeed the use case. However bumping to 1.2.7 does not seem to address the issue. I have:

```
  mjpage(
    jsdom.serializeDocument(document),
    {
      format: 'MathML',
      MathJax: {
        SVG: {
          font:             'STIX-Web',
          useGlobalCache:   false,
          undefinedFamily:  '"Arial Unicode MS", Arial, sans-serif',
          Augment: {
            initSVG () {
              console.log('INITING');
              // ...
            }
          }
        },
      },
    },
    {
      svg:            true,
      useGlobalCache: false,
    },
    (result) => {
      jsdom.env(result, (err, win) => {
         // ...
      });
    }
  );
```

But the `console.log` never shows. It seems like the configuration is taking place but the init is still not being called.

**Comment by pkra** [comment]
Hm. Works for me. https://runkit.com/58ad7e09f01e9600147143f3/58f63a39f41b5b001249bc34

**Comment by pkra** [comment]
@darobin did this resolve for you as well?
