### ISSUE TITLE
options not passed correctly to jsdom [was: jsdom bakes client-side DOM changes to mjpage output?]

### ISSUE THREAD

**Issue by fasiha** [pkra/mathjax-node-page#41]
I was really surprised when my HTML code, which contains both Mathjax and code blocks, came out of mjpage with highlight.js annotations in the code blocks. For example, consider:
```html
<!-- highlight.js stuff -->
<link rel="stylesheet" href="styles/atom-one-dark.css">
<script src="highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<p>
  \(x^y\)
</p>

<pre class="py"><code>import numpy as np</code></pre>
```
mjpage replaces the `pre` tag with the following:
```html
<pre class="py"><code class="hljs python"><span class="hljs-keyword">import</span> numpy <span class="hljs-keyword">as</span> np</code></pre>
```

Reading #15, is this due to jsdom parsing the input HTML, evaluating JS that was intended to run client-side, and hardcoding the resultant DOM in the output of mjpage?

If so, it might be worthwhile to advertise this fact in the `mjpage --help` or the project README.

(Personally this is a really-interesting way to do server-side rendering for me, so I’m happy to discover this trick, and let mjpage do this for me! I just have to strip the JS from the output HTML to prevent it from re-running.)

**Comment by pkra** [comment]
Hm... I thought this was disabled but that might not be the case.

Try setting `FetchExternalResources: false` in the `jsdom` block of your configuration.

**Comment by pkra** [comment]
It's a bug -- `FetchExternalResources` and `ProcessExternalResources` should be wrapped in a `features` block.
