### ISSUE TITLE
mjpage doesn't seem to do anything.

### ISSUE THREAD

**Issue by TedTed** [pkra/mathjax-node-page#48]
Following installation instructions:

    $ npm install mathjax-node-page
    $ node_modules/mathjax-node-page/bin/mjpage

doesn't do anything, the command just hangs. Same if I try to pass some simple HTML:

    $ node_modules/mathjax-node-page/bin/mjpage '<html><head><title>test</title><head><body>test $\alpha \le \beta$</body></html>' > /tmp/test.html

Changing the `--fontURL` option to somewhere I know fonts are installed & available has no effect. There's no error message nor a `--debug` option so I have no idea where to go from there.

I'm using npm version 5.3.0.

**Comment by pkra** [comment]
Thanks for the report. I'll look into why it's not printing the usage when missing input.

From the file source; `Usage: mjpage [options] < input.html > output.html`

But note that single-dollars are not configured by default (just like MathJax). If you need to pass a string, try `mjpage --dollars <<< "<html><head><title>test</title><head><body>test $\alpha \le \beta$</body></html>"`

**Comment by TedTed** [comment]
Thanks for the quick answer. The problem isn't simply there when the input is empty or because I used the wrong notation. Your example also does nothing and hangs, as well as if I simply run `mjpage` with some HTML that doesn't contain any TeX code at all. Essentially, mjpage is not working no matter what.

**Comment by pkra** [comment]
Hm... The code I pasted works fine for me on a clean setup using node 8.2.1 / npm 5.3. Not sure how to help you, I'm afraid.

**Comment by pkra** [comment]
Closing this as abandoned. If there is more information on how to reproduce the problem, I'm happy to revisit this.
