### ISSUE TITLE
Allow to pass custom mathjax-node instance

### ISSUE THREAD

**Issue by roman-spiridonov** [pkra/mathjax-node-page#49]
Say I want to use https://github.com/pkra/mathjax-node-svg2png in mathjax-node-page, and currently the way I see requires creating a fork of mathjax-node-page to customize the mathjax-node parser.
It would be great to have an API that allows to pass custom mathjax-node.

**Comment by pkra** [comment]
I understand the use case for PNG output (I need it myself some times). However, I'm not sure I want to handle this here. Besides the problem of switching out mathjax-node (cf. #14), it would require more extensive changes if you want to do it well (de-duplication, PNG optimization etc).

I'd recommend a more general tool for converting SVG to to PNG as a better approach (and #7 would probably help) but I'd be happy to take a look at PRs with ideas.

**Comment by pkra** [comment]
Fixed by  #50
