### ISSUE TITLE
keep tagnames and attributes untouched

### ISSUE THREAD

**Issue by hjy1210** [pkra/mathjax-node-page#51]
I try to use mathjax-node-page to transform [QTI xml files](http://www.imsglobal.org/question/qtiv2p2/imsqti_v2p2_impl.html) which is a standard in learning/teaching environment.

My original xml document with mathematics in latex code, translation replace latex formula to mathml node.

Unfortunately, after tranlation, all tagnames and attributes have changed to lowercase. For example, `<simpleChoice>` becomes `<simplechoice>`; `<choiceInteraction responseIdentifier...` becomes `<choiceinteraction responseidentifier ...`, which is NOT what QTI want, xml file are case sensitive.

Is there a method to keep all tagnames and attributes untouched.

Why mathjax-node-page forcely change to lower case of all tagnames and attributes?

Thanks

**Comment by pkra** [comment]
This is expected behavior. mathjax-node-page parses input as HTML (using jsdom). HTML is not case-sensitive and jsdom cleans up the tag names as usual.

I don't think mathjax-node-page is the right tool for dealing with XML. One the one hand, jsdom is focused on HTML (at most, xHTML5). On the other hand, in XML any math content is usually structure so the complexity of mathjax-node-page is not needed.

It's easy to write a simple wrapper around mathjax-node, e.g., using [xmldom](https://www.npmjs.com/package/xmldom), e.g.,

```javascript
const DOMParser = require('xmldom').DOMParser;
const mj = require('mathjax-node');

const input = '...' // QTI xml string with mathml
const doc = new DOMParser().parseFromString(input ,'text/xml');
const maths = doc.documentElement.getElementsByTagNameNS(`http://www.w3.org/1998/Math/MathML`, `math`)

for (i =0; i < maths.length; i++) {
const math = maths[i]
mj.typeset({
  math: math.toString(),
  format: "MathML",
  svg: true, // or html
  node: math // custom value to pass node to callback
}, function (data, input) {
  //  do something, e.g., replace input.node with data.svg etc
})
}
```

**Comment by hjy1210** [comment]
@pkra Thank you for your rapid answer.

I DO use `mathjax-node` plus `xmldoc` to finish my job. I am appreciated if you can give some comments about my following code.

My scenario is : translate cmlStr to xmlStr. Where cmlStr is an custom XML string, which contains mathematics encoded in TeX format. xmlStr is the result of replacing TeX scripts in cmlStr with MathML node.

My assumptionis about chunk of mathematics in cmlStr :
*  contained in descendant textNodes of cmlstr,
*  inline-math is delimited by `\(`,`\)` pair; display-math is delimited by `\[`,`\]` pair,
*  `<` character in math content is replaced by `&lt;` and `&` character in math content is replaced by `&amp;`

Although `mathjax-node` can use to typeset chunk of math in TeX to MathML, but the operations are async. So I use Promise.all to sync all chunk results as a whole. Function `toMML` shown below is my implementation.

Please give me some comments, especially:
* Is Promise is necessary/efficient in my problem?
* Is there other better approach?

Thanks again.

```
var DOMParser = require('xmldom').DOMParser
var XMLSerializer = require('xmldom').XMLSerializer

function toMML(data) {
  var res = []
  // replace inline-Tex(delimited by \( and \)) by <mathjax-node class="inline">
  // replace Tex(delimited by \[ and \]) by <mathjax-node class="block">
  var str = data.replace(/(\\\([^<]*?\\\)|\\\[[^<]*?\\\])/g, m => {
    if (m[1] === "(") {
      return `<mathjax-node class="inline">${m.substr(2, m.length - 4)}</mathjax-node>`
    } else {
      return `<mathjax-node class="block">${m.substr(2, m.length - 4)}</mathjax-node>`
    }
  })

  var mjAPI = require("mathjax-node");
  mjAPI.config({
    MathJax: {
      TeX: {
        Macros: { ceec: ['{\\fbox{#1}}', 1] }
      }
    }
  });
  mjAPI.start();

  var doc = new DOMParser().parseFromString(str)
  var docEle = doc.documentElement

  // promises is arrange array of Promises, each entry Promise corresponding to 
  // typesetting one chunk of <mathjax-node>
  var promises = []
  var mathjaxs = docEle.getElementsByTagName('mathjax-node')
  for (var j = mathjaxs.length - 1; j >= 0; j--) {
    const mathnode=mathjaxs[j]
    var promise = new Promise((resolve, reject) => {
      var isInline = mathnode.getAttribute('class') === "inline"
      var options = {
        math: mathnode.childNodes[0].nodeValue,
        format: "TeX", // "inline-TeX", "MathML"
        mml: true, //  svg:true,
      }
      if (isInline) {
        options.format = "inline-TeX"
      }
      mjAPI.typeset(options, (data) => {
        if (data.errors) {
          reject(data.errors)
        } else {
          mathnode.parentNode.replaceChild(new DOMParser().parseFromString(data.mml).documentElement,
            mathnode)
          resolve(data.mml)
        }
      })
    })
    promises.push(promise)
  }

  return new Promise((resolve,reject)=>{
    Promise.all(promises).then(results => {
      resolve(new XMLSerializer().serializeToString(docEle))
    })
  })
}

var cmlStr = `<itemBody>Solution of equation \\(ax^2+bx+c=0\\) is
\\[x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}.\\] Molecular formula of sulfuric acid is
\\(\\ce{H2SO4}\\).</itemBody>`

toMML(cmlStr).then(result=>console.log(result))
```

**Comment by pkra** [comment]
Since 1.2.0, mathjax-node provides a promise API. I would probably just use an async function to loop through some  `await  mjAPI.typeset(options)` but you'd need node 8+ for this.

**Comment by hjy1210** [comment]
@pkra Thank you for your answer and patient.

I need to typeset some physical unit by TeX command `\pu` which is in package mhchem.js(version3).
In default setting `mathjax-node` throw exception `TeX parse error: Undefined control sequence \pu`.

To solve this problem, my steps as follows:
1. copy `mathjax/unpacked/extensions/TeX/mhchem3/mhchem.js` to `mathjax/unpacked/extensions/`.
2. execute sample code below
```
var mjAPI = require("mathjax-node");

mjAPI.config({
  MathJax: {
    extensions: ["mhchem.js"]
  }
});
mjAPI.start();

var options = {
  math: "\\pu{1.0e-20}",
  format: "inline-TeX", // "inline-TeX", "MathML"
  mml: true, //  svg:true,
}

mjAPI.typeset(options, (data) => {
  if (data.errors) {
    console.log(data.errors)
  } else {
    console.log(data.mml)
  }
})
```
3. I Do get what I want, but
  3.1 It spend time almost 17 secs in my machine.
  3.2 It give warning: `File load error: file:///D:/work/qti-demo/node_modules/mathjax/unpacked/extensions/mhchem.js`

Could you tell me how to configure `mathjax-node` about mhchem(version3).

By the way, If I use mathjax in my webpage and configure mathjax below in head section, the page can typeset `\pu` command and response very quickly(less than 1 sec).
```
<script type="text/x-mathjax-config">
  MathJax.Ajax.config.path["mhchem"] = "https://cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.2.0"; 
  MathJax.Hub.Config({
    extensions: ["[mhchem]/mhchem.js"]
  });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```

**Comment by pkra** [comment]
Please post general mathjax and mathjax-node questions to https://groups.google.com/forum/#!forum/mathjax-users. 

But before you do, check http://docs.mathjax.org/en/latest/tex.html#mhchem since mathjax already ships mhchem v3; you just have to load it and configure `legacy:false`. 

(FWIW the delay is a timeout due to a wrong path somewhere.)
