### ISSUE TITLE
mathjax-node-page parsing latex 'def'-like commands

### ISSUE THREAD

**Issue by ronligt** [pkra/mathjax-node-page#52]
Inside our document we style some of the latex-equations using for example `\definecolor`, `\def`, `\newcommand` and `\colorbox`. This worked perfectly in a (much) older version of mathjax-node v.0.5.1 **page2svg**, but we can’t seem to get this to work in the latest version of **mjpage** (mathjax-node-page v.1.4.0).

Can you help us solve this as we would like to know if we can switch to this newer version?

Code snip from `Chap_6.html` (see below):
``` html
<span class="math inline" style="display:none;">\[
\definecolor{mainresultcolor}{rgb}{1,0.6,1}
\newcommand{\mainresult}[1]{
	\colorbox{mainresultcolor}{$#1$}
}
\]</span>
<span class="math display">\[
\mainresult{\begin{array}{*{20}{l}}
{{m_y}}&amp;{ = {m_x}\sum\limits_{k =  - \infty }^{ + \infty } {h[n - k]}  = {m_x}\sum\limits_{n =  - \infty }^{ + \infty } {h[n]} }\\
{\,\,\,}&amp;{ = {m_x}H(\Omega  = 0)}
\end{array}} % end class mainresult
\]</span>
```

This is the error:
``` bash
$ ../node_modules/mathjax-node-page/bin/mjpage < Chap_6.html > test.html
TeX parse error: Undefined control sequence \definecolor
TeX parse error: Undefined control sequence \mainresult
```

**Comment by pkra** [comment]
This problem is due to https://github.com/mathjax/MathJax-node/issues/175.

Running `mjpage --extensions 'TeX/color.js ...` should give the desired result.

**Comment by ronligt** [comment]
Solved the problem!

**Comment by pkra** [comment]
Good to hear. Thanks for the follow up.
