### ISSUE TITLE
[ANNOUNCEMENT] mathjax v3 released

### ISSUE THREAD

**Issue by pkra** [pkra/mathjax-node-page#54]
For those not following the mathjax-dev mailing list or the MathJax/MathJax repository, MathJax v3 is in alpha and currently resides at https://github.com/mathjax/mathjax-v3.

It's a re-write (of most) of MathJax and supports NodeJS out of the box. It provides a (new) architecture for page-wide processing as well and thus (eventually) this code base will become obsolete.

**Comment by PatrickMassot** [comment]
Thank you for these very good news. This looks rather far from being end-user ready though. In the mean time, could you answer [my question](https://github.com/pkra/mathjax-node-page/issues/14#issuecomment-353780022) about sre?

**Comment by pkra** [comment]
v3 is now in beta.

**Comment by pkra** [comment]
MathJax v3 is out. 

This repository will probably retire some time soon.
