### ISSUE TITLE
MathJax_SVG_glyphs missing xmlns

### ISSUE THREAD

**Issue by mitchkeller** [pkra/mathjax-node-page#61]
mathjax-node-page outputs a big `svg` element at the very end of an input (X)HTML file that contains a `defs` with `@id=MathJax_SVG_glyphs`. The `svg` does not have an `@xmlns` attribute set, and this seems to be preventing browsers (or ePub readers, which is my ultimate output destination) from being able to use the definitions. If I add `xmlns="http://www.w3.org/2000/svg"` to that final `svg` element then I get the desired result. I can't figure out what adds that `svg`, so I'm not able to submit a pull request on my own to fix the problem, unfortunately.

**Comment by pkra** [comment]
Thanks for the report. I remember running into the same problem elsewhere and vaguely recollect a jsdom serialization issue. Will have to find time to check. 

FWIW be sure to test support for a global SVG element in epub3 reading systems -- some RSs do not handle them well (though my latest tests indicate that all major RSs are ok now).

**Comment by mitchkeller** [comment]
Having good luck so far with the major ones. Rasterization for Kindle is a different ballgame, unfortunately. (This is all work for the PreTeXt project, btw. Right now it's easy to find the one `svg` missing its `@xmlns` and add it using sed, but it will be great to have this fixed when you have a chance to find the source of the problem.)

**Comment by pkra** [comment]
@mitchkeller I cannot reproduce this on master. Could you give it a try (the code on master has not yet been released).

**Comment by pkra** [comment]
Oh, nevermind. I see it.

**Comment by pkra** [comment]
It looks like a jsdom serialization issue. Adding the namespace as an attribute seems to work.
