### ISSUE TITLE
Use JSDOM document as input and output to avoid reserialization

### ISSUE THREAD

**Issue by bfirsh** [pkra/mathjax-node-page#62]
This is similar to #7, but the fix in there doesn't cover my use case. I have a long chain of processing that passes around a JSDOM document. Before mathjax-node-page, I serialize to a string to pass it to JSDOM, then after, I parse the mathjax-node-page output to get a JSDOM document. This seems a bit silly considering mathjax-node-page is operating on a JSDOM document.

I want to be able to provide a complete JSDOM document as input, and receive a JSDOM document as output. Ideally, just modified in place for best performance.

**Comment by pkra** [comment]
Definitely a good idea but I don't plan to work on this any time soon.

Happy to review a PR.

**Comment by pkra** [comment]
Also, if this ideas comes from your work on arxiv-vanity, then I suspect it might be easier to write your own wrapper around mathjax-node -- just picking up LaTeXML-specific markup etc.
