### ISSUE TITLE
* child_process in ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js

### ISSUE THREAD

**Issue by blueshu** [pkra/mathjax-node-page#68]
When I try to add  "import mjnode from 'mathjax-node-page'“ in my page , I got a error:
This dependency was not found:

* child_process in ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js

To install it, you can run: npm install --save child_process

Is this mean I should install child_process??

**Comment by pkra** [comment]
I'm afraid I can't reproduce the problem. Are you trying to bundle something for client-side use by any chance?

**Comment by pkra** [comment]
> I import it in nextJS project and it's worked on client side. 

Fascinating. I don't see how that could work given MathJax's custom module system.

But in a React context you might want to checkout the [beta version of MathJax v3](https://github.com/mathjax/mathjax-v3/) -- it doesn't require a DOM but you can write a custom adaptor for whatever vdom you're using.

**Comment by blueshu** [comment]
ok， thanks

**Comment by pkra** [comment]
No problem. I didn't mention it but since v3 is written in Typescript, you can use it with any module format that TS supports -- none of which existed when MathJax's v2 module system was designed.
