### ISSUE TITLE
cant specify undefinedFamily in svg

### ISSUE THREAD

**Issue by Ir1d** [pkra/mathjax-node-page#70]
Hi, thx for this nice tool. I've met a small problem in specifying font of Chinese characters in rendered svg.
```js
mjpage(input, {
          format: ["TeX"], Mathjax: {
            font: 'STIX-Web',
			SVG:{
	            undefinedFamily: '"Arial Unicode MS", Arial, sans-serif',
			}
          }
        }, { svg: true }, function (output) {
          // console.log(output); // resulting HTML string
          // console.log(filename)
          console.log('Finished rendering: ', filename);
          fs.writeFileSync(filename, output, 'utf-8');
        });
```

This is resulting in `<text font-family="monospace" stroke="none" transform="scale(71.759) matrix(1 0 0 -1 0 0)">情</text>`

While instead I was expecting the font family to be something like `STIXGeneral,'Arial Unicode MS',serif`.

Any idea on how to change this font-family?
Thx in advance.

FYI: client-side mathjax results in `<text font-family="STIXGeneral,'Arial Unicode MS',serif" stroke="none" transform="scale(51.054) matrix(1 0 0 -1 0 0)">情</text>` 

upd: https://github.com/mathjax/MathJax-node/blob/08f566cffb7c4c55098b1ce9315dc0efc9c443a0/lib/main.js#L328

**Comment by Ir1d** [comment]
I modified this line manually: https://github.com/mathjax/MathJax-node/blob/08f566cffb7c4c55098b1ce9315dc0efc9c443a0/lib/main.js#L328

However, it seems that the problem is not from the font.

I'm receiving this, the characters overlap with each other.

![image](https://user-images.githubusercontent.com/10709657/44958662-e242c200-af15-11e8-8787-8f32cf507172.png)

**Comment by pkra** [comment]
This issue seems to be about mathjax-node not mathjax-node-page.

Mathjax-node has a `cjkCharWidth` option to tweak CJK characters fallback behavior, cf. https://github.com/mathjax/MathJax-node/#typesetoptions-callback. 

If that doesn't help, please file an issue upstream at mathjax-node.

**Comment by Ir1d** [comment]
@pkra Thx for replying. But that option doesn't work either.(or perhaps I used them in a wrong way)

I've opened at https://github.com/mathjax/MathJax-node/issues/424
